
# Default state for all rules
default: true

# Examples: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD013/line-length - Line length
MD013: false
# MD025/single-title/single-h1 Multiple top-level headings in the same document
MD025: false

# MD029/ol-prefix : Ordered list item prefix
MD029: false

# MD039/no-space-in-links
MD039: false

# MD041/first-line-heading/first-line-h1: First line in a file should be a top-level headingmarkdownlintMD041
MD041: false

# MD049/emphasis-style : Emphasis style
MD049: false

# MD051/link-fragments : Link fragments should be valid
MD051: false

# MD052/reference-links-images : Reference links and images should use a label that is defined
MD052: false
