# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-plots-balances
channels:
- conda-forge
dependencies:
- python>=3.8
- pip

- pypsa

- pandas >=2.1
- numpy >=1.26.4

- atlite >=0.3
- cartopy >=0.25.0
- fiona >=1.10.1
- folium >=0.20.0
- geojson >=3.2.0
- geopandas >=1
- geopy >=2.4.1
- matplotlib >=3.10.7
- plotly >=6.4.0
- yaml >=0.2.5

- pre-commit
- black

  # Keep in conda environment when calling ipython
- ipython
- jupyter >=1.1.1
- ipykernel
